2015/04/02 10:09:15 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /var/www/html/yii/db/CDbConnection.php:399
Stack trace:
#0 /var/www/html/yii/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/html/yii/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/html/yii/base/CModule.php(394): CDbConnection->init()
#3 /var/www/html/yii/base/CApplication.php(458): CModule->getComponent('db')
#4 /var/www/html/yii/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /var/www/html/yii/db/ar/CActiveRecord.php(1433): CActiveRecord->getDbConnection()
#6 /var/www/html/yii/db/ar/CActiveRecord.php(1522): CActiveRecord->getTableAlias(true)
#7 /var/www/html/lilely.localhost/protected/components/WebSetting.php(17): CActiveRecord->findByAttributes(Array)
#8 /var/www/html/lilely.localhost/protected/controllers/HomeController.php(13): WebSetting->getValue('SIZE_OF_STORY')
#9 /var/www/html/yii/web/CWebApplication.php(281): HomeController->init()
#10 /var/www/html/yii/web/CWebApplication.php(141): CWebApplication->runController('')
#11 /var/www/html/yii/base/CApplication.php(184): CWebApplication->processRequest()
#12 /var/www/html/lilely.localhost/index.php(14): CApplication->run()
#13 {main}
REQUEST_URI=/
---
2015/04/02 10:10:26 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /var/www/html/yii/db/CDbConnection.php:399
Stack trace:
#0 /var/www/html/yii/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/html/yii/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/html/yii/base/CModule.php(394): CDbConnection->init()
#3 /var/www/html/yii/base/CApplication.php(458): CModule->getComponent('db')
#4 /var/www/html/yii/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /var/www/html/yii/db/ar/CActiveRecord.php(1433): CActiveRecord->getDbConnection()
#6 /var/www/html/yii/db/ar/CActiveRecord.php(1522): CActiveRecord->getTableAlias(true)
#7 /var/www/html/lilely.localhost/protected/components/WebSetting.php(17): CActiveRecord->findByAttributes(Array)
#8 /var/www/html/lilely.localhost/protected/controllers/HomeController.php(13): WebSetting->getValue('SIZE_OF_STORY')
#9 /var/www/html/yii/web/CWebApplication.php(281): HomeController->init()
#10 /var/www/html/yii/web/CWebApplication.php(141): CWebApplication->runController('')
#11 /var/www/html/yii/base/CApplication.php(184): CWebApplication->processRequest()
#12 /var/www/html/lilely.localhost/index.php(14): CApplication->run()
#13 {main}
REQUEST_URI=/
---
2015/04/02 10:10:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /var/www/html/yii/db/CDbConnection.php:399
Stack trace:
#0 /var/www/html/yii/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/html/yii/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/html/yii/base/CModule.php(394): CDbConnection->init()
#3 /var/www/html/yii/base/CApplication.php(458): CModule->getComponent('db')
#4 /var/www/html/yii/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /var/www/html/yii/db/ar/CActiveRecord.php(1433): CActiveRecord->getDbConnection()
#6 /var/www/html/yii/db/ar/CActiveRecord.php(1522): CActiveRecord->getTableAlias(true)
#7 /var/www/html/lilely.localhost/protected/components/WebSetting.php(17): CActiveRecord->findByAttributes(Array)
#8 /var/www/html/lilely.localhost/protected/controllers/HomeController.php(13): WebSetting->getValue('SIZE_OF_STORY')
#9 /var/www/html/yii/web/CWebApplication.php(281): HomeController->init()
#10 /var/www/html/yii/web/CWebApplication.php(141): CWebApplication->runController('')
#11 /var/www/html/yii/base/CApplication.php(184): CWebApplication->processRequest()
#12 /var/www/html/lilely.localhost/index.php(14): CApplication->run()
#13 {main}
REQUEST_URI=/
---
2015/04/02 10:10:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /var/www/html/yii/db/CDbConnection.php:399
Stack trace:
#0 /var/www/html/yii/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/html/yii/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/html/yii/base/CModule.php(394): CDbConnection->init()
#3 /var/www/html/yii/base/CApplication.php(458): CModule->getComponent('db')
#4 /var/www/html/yii/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /var/www/html/yii/db/ar/CActiveRecord.php(1433): CActiveRecord->getDbConnection()
#6 /var/www/html/yii/db/ar/CActiveRecord.php(1522): CActiveRecord->getTableAlias(true)
#7 /var/www/html/lilely.localhost/protected/components/WebSetting.php(17): CActiveRecord->findByAttributes(Array)
#8 /var/www/html/lilely.localhost/protected/controllers/HomeController.php(13): WebSetting->getValue('SIZE_OF_STORY')
#9 /var/www/html/yii/web/CWebApplication.php(281): HomeController->init()
#10 /var/www/html/yii/web/CWebApplication.php(141): CWebApplication->runController('')
#11 /var/www/html/yii/base/CApplication.php(184): CWebApplication->processRequest()
#12 /var/www/html/lilely.localhost/index.php(14): CApplication->run()
#13 {main}
REQUEST_URI=/
---
2015/04/02 10:14:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /var/www/html/yii/db/CDbConnection.php:399
Stack trace:
#0 /var/www/html/yii/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/html/yii/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/html/yii/base/CModule.php(394): CDbConnection->init()
#3 /var/www/html/yii/base/CApplication.php(458): CModule->getComponent('db')
#4 /var/www/html/yii/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /var/www/html/yii/db/ar/CActiveRecord.php(1433): CActiveRecord->getDbConnection()
#6 /var/www/html/yii/db/ar/CActiveRecord.php(1522): CActiveRecord->getTableAlias(true)
#7 /var/www/html/lilely.localhost/protected/components/WebSetting.php(17): CActiveRecord->findByAttributes(Array)
#8 /var/www/html/lilely.localhost/protected/controllers/HomeController.php(13): WebSetting->getValue('SIZE_OF_STORY')
#9 /var/www/html/yii/web/CWebApplication.php(281): HomeController->init()
#10 /var/www/html/yii/web/CWebApplication.php(141): CWebApplication->runController('')
#11 /var/www/html/yii/base/CApplication.php(184): CWebApplication->processRequest()
#12 /var/www/html/lilely.localhost/index.php(14): CApplication->run()
#13 {main}
REQUEST_URI=/
---
2015/04/02 10:14:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /var/www/html/yii/db/CDbConnection.php:399
Stack trace:
#0 /var/www/html/yii/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/html/yii/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/html/yii/base/CModule.php(394): CDbConnection->init()
#3 /var/www/html/yii/base/CApplication.php(458): CModule->getComponent('db')
#4 /var/www/html/yii/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /var/www/html/yii/db/ar/CActiveRecord.php(1433): CActiveRecord->getDbConnection()
#6 /var/www/html/yii/db/ar/CActiveRecord.php(1522): CActiveRecord->getTableAlias(true)
#7 /var/www/html/lilely.localhost/protected/components/WebSetting.php(17): CActiveRecord->findByAttributes(Array)
#8 /var/www/html/lilely.localhost/protected/controllers/HomeController.php(13): WebSetting->getValue('SIZE_OF_STORY')
#9 /var/www/html/yii/web/CWebApplication.php(281): HomeController->init()
#10 /var/www/html/yii/web/CWebApplication.php(141): CWebApplication->runController('')
#11 /var/www/html/yii/base/CApplication.php(184): CWebApplication->processRequest()
#12 /var/www/html/lilely.localhost/index.php(14): CApplication->run()
#13 {main}
REQUEST_URI=/
---
2015/04/02 18:18:40 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in D:\xampp\htdocs\yii\db\CDbConnection.php:382
Stack trace:
#0 D:\xampp\htdocs\yii\db\CDbConnection.php(330): CDbConnection->open()
#1 D:\xampp\htdocs\yii\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 D:\xampp\htdocs\yii\base\CModule.php(387): CDbConnection->init()
#3 D:\xampp\htdocs\yii\base\CApplication.php(450): CModule->getComponent('db')
#4 D:\xampp\htdocs\yii\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 D:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1428): CActiveRecord->getDbConnection()
#6 D:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1517): CActiveRecord->getTableAlias(true)
#7 D:\xampp\htdocs\lilely-quote\protected\components\WebSetting.php(17): CActiveRecord->findByAttributes(Array)
#8 D:\xampp\htdocs\lilely-quote\protected\controllers\HomeController.php(13): WebSetting->getValue('SIZE_OF_STORY')
#9 D:\xampp\htdocs\yii\web\CWebApplication.php(281): HomeController->init()
#10 D:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController(false)
#11 D:\xampp\htdocs\yii\base\CApplication.php(180): CWebApplication->processRequest()
#12 D:\xampp\htdocs\lilely-quote\index.php(14): CApplication->run()
#13 {main}
REQUEST_URI=/en/
---
2015/04/02 18:18:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\xampp\htdocs\yii\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\xampp\htdocs\lilely-quote\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/en/favicon.ico
---
2015/04/02 18:18:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\xampp\htdocs\yii\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\xampp\htdocs\lilely-quote\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/en/favicon.ico
---
2015/04/02 18:18:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\xampp\htdocs\yii\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\xampp\htdocs\lilely-quote\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/en/favicon.ico
---
